version: '3'
services:
  web:
    image: "swinxyapps/stack.php:7.0"
    environment:
      APP_NAME: example
      APP_CONF: |-
        php:
          composer:
            auth:
              basic:
                - url: "http://repo.magento.com"
                  username: "username"
                  password: "password"
    volumes:
      - ./:/application
